# Generated by Django 3.2.3 on 2021-05-25 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=30)),
                ('subnum', models.CharField(default=None, max_length=20)),
                ('professor', models.CharField(default=None, max_length=20)),
                ('subtime', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=None, max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('major', models.CharField(default=None, max_length=20)),
                ('studentid', models.CharField(default=None, max_length=20)),
                ('introduce', models.TextField(default=None)),
                ('matewant', models.BooleanField(default=False)),
                ('photo', models.ImageField(default='media/photo/default_photo.png', upload_to='photo')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PLR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='account.profile')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.profile')),
            ],
        ),
    ]
