# Generated by Django 3.2.3 on 2021-05-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/photo/default_photo.png', upload_to='photo'),
        ),
    ]
