# Generated by Django 3.2.3 on 2021-05-23 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=30)),
                ('subnum', models.CharField(default=None, max_length=20)),
                ('professor', models.CharField(default=None, max_length=20)),
                ('subtime', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='introduce',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='matewant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='studentid',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PLR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='account.profile')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.profile')),
            ],
        ),
    ]
