# Generated by Django 3.2.3 on 2021-05-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20210523_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='account.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('content', models.TextField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='account.profile')),
                ('community', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.community')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='account.profile')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post')),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms1', to='account.profile')),
                ('profile2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms2', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('read', models.BooleanField(default=False)),
                ('chatroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='community.chatroom')),
                ('pfrom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='send_chats', to='account.profile')),
                ('pto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receive_chats', to='account.profile')),
            ],
        ),
    ]
